# Generated by Django 4.2.9 on 2024-02-01 05:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_post_author_alter_post_body_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "分类", "verbose_name_plural": "分类"},
        ),
        migrations.AlterModelOptions(
            name="post", options={"verbose_name": "文章", "verbose_name_plural": "文章"},
        ),
        migrations.AlterModelOptions(
            name="tag", options={"verbose_name": "标签", "verbose_name_plural": "标签"},
        ),
        migrations.AlterField(
            model_name="post",
            name="created_time",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="创建时间"
            ),
        ),
    ]
